//go:build !noembed

// Code generated by generate.go; DO NOT EDIT.

package bundled

import (
	"io/fs"

	_ "embed"
)

//go:embed libs/lib.luajit.d.tlua
var libs_lib_luajit_d_tlua string

var embeddedContents = map[string]string{
	"libs/lib.luajit.d.tlua": libs_lib_luajit_d_tlua,
}

var libsEntries = []fs.DirEntry{
	&fileInfo{name: "lib.luajit.d.tlua", size: int64(len(libs_lib_luajit_d_tlua))},
}
