//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
)

var (
	luaLibInputDir = "lualibs"

	// Gate: no rest parameter may survive anywhere in the generated output.
	// The hand-written lualibs must use tlua's nameless vararg form. Two
	// shapes, because a rest can be introduced by a name or by a binding
	// pattern; a bare `...` in a *type* (`(...any)`, `[a: number, ...boolean[]]`)
	// is a pack tail, is legal, and matches neither.
	reNamedRest   = regexp.MustCompile(`\.\.\.\w+\s*\??\s*:`)
	reBindingRest = regexp.MustCompile(`\.\.\.\s*[\[{]`)
)

func main() {
	log.SetFlags(log.LstdFlags | log.Lshortfile)

	libs := readLibs()
	generateLibs(libs)
	generateLibList(libs)
	generateEmbedded(libs)
}

type lib struct {
	target    string   // target relative to libs dir
	sourceDir string   // directory containing sources
	sources   []string // sources relative to sourceDir
}

func generateLibs(libs []lib) {
	const outputDir = "libs"

	if err := os.RemoveAll(outputDir); err != nil {
		log.Fatalf("failed to remove libs directory: %v", err)
	}

	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		log.Fatalf("failed to create libs directory: %v", err)
	}

	for _, lib := range libs {
		var output bytes.Buffer
		for _, source := range lib.sources {
			sourcePath := filepath.Join(lib.sourceDir, source)
			b, err := os.ReadFile(sourcePath)
			if err != nil {
				log.Fatalf("failed to read %s: %v", sourcePath, err)
			}

			output.WriteByte('\n')
			output.Write(removeCRLF(b))
		}

		if named := reNamedRest.FindAll(output.Bytes(), -1); named != nil {
			log.Fatalf("%s still declares %d named rest parameter(s), e.g. %q; tlua varargs have no name -- rewrite the lualib by hand", lib.target, len(named), named[0])
		}
		if bound := reBindingRest.FindAll(output.Bytes(), -1); bound != nil {
			log.Fatalf("%s still declares %d binding-pattern rest parameter(s), e.g. %q; tlua has no rest destructuring -- rewrite the lualib by hand", lib.target, len(bound), bound[0])
		}

		outputPath := filepath.Join(outputDir, lib.target)
		if err := os.WriteFile(outputPath, output.Bytes(), 0o644); err != nil {
			log.Fatalf("failed to write %s: %v", outputPath, err)
		}
	}
}

func generateLibList(libs []lib) {
	var code bytes.Buffer
	code.WriteString("// Code generated by generate.go; DO NOT EDIT.\n\n")
	code.WriteString("package bundled\n\n")

	code.WriteString("// LibNames is the list of all bundled lib files, sorted by name.\n")
	code.WriteString("// For the list of libs sorted by load order, use [tsoptions.Libs].\n")
	code.WriteString("var LibNames = []string{\n")
	for _, lib := range libs {
		code.WriteString("\t\"" + lib.target + "\",\n")
	}
	code.WriteString("}\n")

	writeCode("libs_generated.go", code.Bytes())
}

func generateEmbedded(libs []lib) {
	libVarNames := make([]string, len(libs))
	for i, lib := range libs {
		libVarNames[i] = "libs_" + strings.ReplaceAll(lib.target, ".", "_")
	}

	var code bytes.Buffer
	code.WriteString("//go:build !noembed\n\n")
	code.WriteString("// Code generated by generate.go; DO NOT EDIT.\n\n")
	code.WriteString("package bundled\n\n")
	code.WriteString("import (\n")
	code.WriteString("\"io/fs\"\n\n")
	code.WriteString("_ \"embed\"\n")
	code.WriteString(")\n\n")

	// gofumpt (used by `hereby format`) unwraps a single-declaration `var (…)`
	// block into the bare `var x string` form, while gofmt (used here) keeps the
	// block. Emit the bare form directly for a single lib so the generator output
	// already matches gofumpt — otherwise the `generate` and `check:format` CI
	// jobs disagree and the file flip-flops. Multiple libs stay grouped, which
	// gofumpt also leaves alone.
	if len(libs) == 1 {
		code.WriteString("//go:embed libs/" + libs[0].target + "\n")
		code.WriteString("var " + libVarNames[0] + " string\n\n")
	} else {
		code.WriteString("var (\n")
		for i, lib := range libs {
			varName := libVarNames[i]
			code.WriteString("//go:embed libs/" + lib.target + "\n")
			code.WriteString("" + varName + " string\n")
		}
		code.WriteString(")\n\n")
	}

	code.WriteString("var embeddedContents = map[string]string{\n")
	for i, lib := range libs {
		varName := libVarNames[i]
		code.WriteString("\t\"libs/" + lib.target + "\": " + varName + ",\n")
	}
	code.WriteString("}\n\n")

	code.WriteString("var libsEntries = []fs.DirEntry{\n")
	for i, lib := range libs {
		varName := libVarNames[i]
		fmt.Fprintf(&code, "\t&fileInfo{name: %q, size: int64(len(%s))},\n", lib.target, varName)
	}
	code.WriteString("}\n")

	writeCode("embed_generated.go", code.Bytes())
}

func readLibs() []lib {
	// Lua libraries are maintained by hand in lualibs/. Add new runtime
	// variants here as they are supported.
	libs := []lib{{
		target:    "lib.luajit.d.tlua",
		sourceDir: luaLibInputDir,
		sources: []string{
			"builtin.d.tlua",
			"metatable.d.tlua",
			"global.d.tlua",
			"coroutine.d.tlua",
			"string.d.tlua",
			"table.d.tlua",
			"math.d.tlua",
			"io.d.tlua",
			"os.d.tlua",
			"package.d.tlua",
			"debug.d.tlua",
			"bit.d.tlua",
			"jit.d.tlua",
			"ffi.d.tlua",
			"jit/profile.d.tlua",
			"jit/util.d.tlua",
			"string/buffer.d.tlua",
			"table/clear.d.tlua",
			"table/new.d.tlua",
			"require.d.tlua",
		},
	}}

	slices.SortFunc(libs, func(a lib, b lib) int {
		return strings.Compare(a.target, b.target)
	})

	return libs
}

func removeCRLF(b []byte) []byte {
	return bytes.ReplaceAll(b, []byte("\r\n"), []byte("\n"))
}

func writeCode(filename string, code []byte) {
	formatted, err := format.Source(code)
	if err != nil {
		log.Fatalf("failed to format source: %v", err)
	}

	if err := os.WriteFile(filename, formatted, 0o644); err != nil {
		log.Fatalf("failed to write %s: %v", filename, err)
	}
}
