// Code generated by generate.go; DO NOT EDIT.

package bundled

// LibNames is the list of all bundled lib files, sorted by name.
// For the list of libs sorted by load order, use [tsoptions.Libs].
var LibNames = []string{
	"lib.luajit.d.tlua",
}
