// Code generated by "stringer -type=ScriptKind -output=scriptkind_stringer_generated.go"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ScriptKindUnknown-0]
	_ = x[ScriptKindJS-1]
	_ = x[ScriptKindTS-2]
	_ = x[ScriptKindExternal-3]
	_ = x[ScriptKindJSON-4]
	_ = x[ScriptKindDeferred-5]
}

const _ScriptKind_name = "ScriptKindUnknownScriptKindJSScriptKindTSScriptKindExternalScriptKindJSONScriptKindDeferred"

var _ScriptKind_index = [...]uint8{0, 17, 29, 41, 59, 73, 91}

func (i ScriptKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ScriptKind_index)-1 {
		return "ScriptKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ScriptKind_name[_ScriptKind_index[idx]:_ScriptKind_index[idx+1]]
}
