//go:build ignore

package main

import (
	"bytes"
	"cmp"
	"compress/gzip"
	"flag"
	"fmt"
	"go/format"
	"go/token"
	"log"
	"maps"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"slices"
	"strconv"
	"strings"
	"unicode"

	"github.com/apyrr/tlua/internal/json"
	"golang.org/x/text/language"
)

type diagnosticMessage struct {
	Category           string `json:"category"`
	Code               int    `json:"code"`
	ReportsUnnecessary bool   `json:"reportsUnnecessary"`
	ReportsDeprecated  bool   `json:"reportsDeprecated"`
	// spelling error here is [sic] in Strada
	ElidedInCompatibilityPyramid bool `json:"elidedInCompatabilityPyramid"`

	key string
}

func main() {
	log.SetFlags(log.LstdFlags | log.Lshortfile)

	diagnosticsOutput := flag.String("diagnostics", "", "path to the output diagnostics_generated.go file")
	locOutput := flag.String("loc", "", "path to the output loc_generated.go file")
	locDir := flag.String("locdir", "", "directory holding the translation archive (<tag>.json.gz) and english.json, read but never written")
	flag.Parse()

	if *diagnosticsOutput == "" || *locOutput == "" || *locDir == "" {
		flag.Usage()
		return
	}

	_, filename, _, ok := runtime.Caller(0)
	if !ok {
		panic("could not get current filename")
	}
	filename = filepath.FromSlash(filename) // runtime.Caller always returns forward slashes; https://go.dev/issues/3335, https://go.dev/cl/603275

	// diagnosticMessages.json is the one source of every message tlua reports.
	// (It began as TypeScript's file merged with tlua's additions; the upstream
	// file is no longer read, so a message is added, reworded or removed here.)
	diagnosticMessages := slices.Collect(maps.Values(readRawMessages(filepath.Join(filepath.Dir(filename), "diagnosticMessages.json"))))

	slices.SortFunc(diagnosticMessages, func(a *diagnosticMessage, b *diagnosticMessage) int {
		return cmp.Compare(a.Code, b.Code)
	})

	// Map each message's key to its current text, for vetting translations. Keys
	// embed the code, which readRawMessages keeps unique; two messages that derive
	// the same variable name would not compile, so that is rejected here.
	messageTexts := make(map[string]string, len(diagnosticMessages))
	varNames := make(map[string]int, len(diagnosticMessages))
	for _, m := range diagnosticMessages {
		varName, key := convertPropertyName(m.key, m.Code)
		if code, ok := varNames[varName]; ok {
			log.Fatalf("diagnostics %d and %d both derive the name %s", code, m.Code, varName)
		}
		varNames[varName] = m.Code
		messageTexts[key] = m.key
	}

	// Generate diagnostics file
	diagnosticsBuf := generateDiagnostics(diagnosticMessages)

	formatted, err := format.Source(diagnosticsBuf.Bytes())
	if err != nil {
		log.Fatalf("failed to format diagnostics output: %v", err)
		return
	}

	if err := os.WriteFile(*diagnosticsOutput, formatted, 0o666); err != nil {
		log.Fatalf("failed to write diagnostics output: %v", err)
		return
	}

	// Generate localizations file
	locBuf := generateLocalizations(messageTexts, *locDir)

	formatted, err = format.Source(locBuf.Bytes())
	if err != nil {
		log.Fatalf("failed to format localizations output: %v", err)
		return
	}

	if err := os.WriteFile(*locOutput, formatted, 0o666); err != nil {
		log.Fatalf("failed to write localizations output: %v", err)
		return
	}
}

func generateDiagnostics(diagnosticMessages []*diagnosticMessage) *bytes.Buffer {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by generate.go; DO NOT EDIT.\n")
	buf.WriteString("\n")
	buf.WriteString("package diagnostics\n")

	for _, m := range diagnosticMessages {
		varName, key := convertPropertyName(m.key, m.Code)

		fmt.Fprintf(&buf, "var %s = &Message{code: %d, category: Category%s, key: %q, text: %q", varName, m.Code, m.Category, key, m.key)

		if m.ReportsUnnecessary {
			buf.WriteString(`, reportsUnnecessary: true`)
		}
		if m.ElidedInCompatibilityPyramid {
			buf.WriteString(`, elidedInCompatibilityPyramid: true`)
		}
		if m.ReportsDeprecated {
			buf.WriteString(`, reportsDeprecated: true`)
		}

		buf.WriteString("}\n\n")
	}

	buf.WriteString("func keyToMessage(key Key) *Message {\n")
	buf.WriteString("\tswitch key {\n")
	for _, m := range diagnosticMessages {
		_, key := convertPropertyName(m.key, m.Code)
		varName, _ := convertPropertyName(m.key, m.Code)
		fmt.Fprintf(&buf, "\tcase %q:\n\t\treturn %s\n", key, varName)
	}
	buf.WriteString("\tdefault:\n\t\treturn nil\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n")

	return &buf
}

// generateLocalizations writes loc_generated.go, which embeds the translation
// archive loc/<tag>.json.gz exactly as it is. The archive was imported from
// TypeScript's localization files and is never rewritten, so no translation is
// lost to a rewording. Instead loc/english.json records the English text each
// archived translation was made from, and a translation is used only while its
// message still has exactly that text. A reworded message falls back to English
// rather than showing a translation of its old wording -- even when its key
// survives the rewording, as keys keep only the first 100 characters of the text.
func generateLocalizations(messageTexts map[string]string, locDir string) *bytes.Buffer {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by generate.go; DO NOT EDIT.\n")
	buf.WriteString("\n")
	buf.WriteString("package diagnostics\n")
	buf.WriteString("\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"compress/gzip\"\n")
	buf.WriteString("\t_ \"embed\"\n")
	buf.WriteString("\t\"strings\"\n")
	buf.WriteString("\t\"sync\"\n")
	buf.WriteString("\t\"golang.org/x/text/language\"\n")
	buf.WriteString("\t\"github.com/apyrr/tlua/internal/json\"\n")
	buf.WriteString(")\n")

	var english map[string]string
	readJSON(filepath.Join(locDir, "english.json"), &english)

	localeFiles, err := filepath.Glob(filepath.Join(locDir, "*.json.gz"))
	if err != nil {
		log.Fatalf("failed to find locale files: %v", err)
	}
	if len(localeFiles) == 0 {
		log.Fatalf("no locale files found in %s", locDir)
	}
	slices.Sort(localeFiles)

	type localeInfo struct {
		varName  string
		tgtCul   string
		filename string
	}

	var locales []localeInfo
	stale := make(map[string]bool)

	for _, localeFile := range localeFiles {
		for key := range readLocaleData(localeFile) {
			source, ok := english[key]
			if !ok {
				log.Fatalf("%s: translation %q has no English text recorded in english.json", localeFile, key)
			}
			if text, ok := messageTexts[key]; ok && text != source {
				stale[key] = true
			}
		}

		filename := filepath.Base(localeFile)
		tgtCul := strings.TrimSuffix(filename, ".json.gz")
		if _, err := language.Parse(tgtCul); err != nil {
			log.Fatalf("failed to parse locale %q: %v", tgtCul, err)
		}
		locales = append(locales, localeInfo{
			// Convert locale code to valid Go identifier
			varName:  strings.ReplaceAll(strings.ReplaceAll(tgtCul, "-", ""), "_", ""),
			tgtCul:   tgtCul,
			filename: filename,
		})
	}

	// Generate matcher with inlined tags
	// English is first (index 0) as the default/fallback with no translation needed
	buf.WriteString("\nvar matcher = language.NewMatcher([]language.Tag{\n")
	buf.WriteString("\tlanguage.English,\n")
	for _, loc := range locales {
		fmt.Fprintf(&buf, "\tlanguage.MustParse(%q),\n", loc.tgtCul)
	}
	buf.WriteString("})\n")

	// Generate index-to-function map for matcher results
	// English (index 0) returns nil since we use the default English text
	buf.WriteString("\nvar localeFuncs = []func() map[Key]string{\n")
	buf.WriteString("\tnil, // English (default)\n")
	for _, loc := range locales {
		fmt.Fprintf(&buf, "\t%s,\n", loc.varName)
	}
	buf.WriteString("}\n")

	buf.WriteString("\n// staleTranslations lists the messages whose archived translations were made\n")
	buf.WriteString("// from different English text than they have now.\n")
	buf.WriteString("var staleTranslations = []Key{\n")
	for _, key := range slices.Sorted(maps.Keys(stale)) {
		fmt.Fprintf(&buf, "\t%q,\n", key)
	}
	buf.WriteString("}\n")

	// Generate helper function for decompressing locale data
	buf.WriteString("\nfunc loadLocaleData(data string) map[Key]string {\n")
	buf.WriteString("\tgr, err := gzip.NewReader(strings.NewReader(data))\n")
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\tpanic(\"failed to create gzip reader: \" + err.Error())\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tdefer gr.Close()\n")
	buf.WriteString("\tvar result map[Key]string\n")
	buf.WriteString("\tif err := json.UnmarshalRead(gr, &result); err != nil {\n")
	buf.WriteString("\t\tpanic(\"failed to unmarshal locale data: \" + err.Error())\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tfor _, key := range staleTranslations {\n")
	buf.WriteString("\t\tdelete(result, key)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn result\n")
	buf.WriteString("}\n")

	// Generate embed directives, vars, and loader functions interleaved at the bottom
	for _, loc := range locales {
		fmt.Fprintf(&buf, "\n//go:embed loc/%s\n", loc.filename)
		fmt.Fprintf(&buf, "var %sData string\n", loc.varName)
		fmt.Fprintf(&buf, "\nvar %s = sync.OnceValue(func() map[Key]string {\n", loc.varName)
		fmt.Fprintf(&buf, "\treturn loadLocaleData(%sData)\n", loc.varName)
		buf.WriteString("})\n")
	}

	return &buf
}

func readJSON(p string, out any) {
	file, err := os.Open(p)
	if err != nil {
		log.Fatalf("failed to open file: %v", err)
	}
	defer file.Close()
	if err := json.UnmarshalRead(file, out); err != nil {
		log.Fatalf("failed to decode %s: %v", p, err)
	}
}

func readRawMessages(p string) map[int]*diagnosticMessage {
	var rawMessages map[string]*diagnosticMessage
	readJSON(p, &rawMessages)

	codeToMessage := make(map[int]*diagnosticMessage, len(rawMessages))
	for k, m := range rawMessages {
		m.key = k
		if other, ok := codeToMessage[m.Code]; ok {
			log.Fatalf("diagnostic code %d is used by both %q and %q", m.Code, other.key, k)
		}
		codeToMessage[m.Code] = m
	}

	return codeToMessage
}

func readLocaleData(p string) map[string]string {
	file, err := os.Open(p)
	if err != nil {
		log.Fatalf("failed to open locale file %s: %v", p, err)
	}
	defer file.Close()

	gr, err := gzip.NewReader(file)
	if err != nil {
		log.Fatalf("failed to read locale file %s: %v", p, err)
	}
	defer gr.Close()

	var messages map[string]string
	if err := json.UnmarshalRead(gr, &messages); err != nil {
		log.Fatalf("failed to decode locale file %s: %v", p, err)
	}
	return messages
}

var (
	multipleUnderscoreRegexp           = regexp.MustCompile(`_+`)
	leadingUnderscoreUnlessDigitRegexp = regexp.MustCompile(`^_+(\D)`)
	trailingUnderscoreRegexp           = regexp.MustCompile(`_$`)
)

func convertPropertyName(origName string, code int) (varName string, key string) {
	var b strings.Builder
	b.Grow(len(origName))

	for _, r := range origName {
		switch r {
		case '*':
			b.WriteString("_Asterisk")
		case '/':
			b.WriteString("_Slash")
		case ':':
			b.WriteString("_Colon")
		default:
			if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
				b.WriteRune('_')
			} else {
				b.WriteRune(r)
			}
		}
	}

	varName = b.String()
	// get rid of all multi-underscores
	varName = multipleUnderscoreRegexp.ReplaceAllString(varName, "_")
	// remove any leading underscore, unless it is followed by a number.
	varName = leadingUnderscoreUnlessDigitRegexp.ReplaceAllString(varName, "$1")
	// get rid of all trailing underscores.
	varName = trailingUnderscoreRegexp.ReplaceAllString(varName, "")

	key = varName
	if len(key) > 100 {
		key = key[:100]
	}
	key = key + "_" + strconv.Itoa(code)

	if !token.IsExported(varName) {
		var b strings.Builder
		b.Grow(len(varName) + 2)
		if varName[0] == '_' {
			b.WriteString("X")
		} else {
			b.WriteString("X_")
		}
		b.WriteString(varName)
		varName = b.String()
	}

	if !token.IsIdentifier(varName) || !token.IsExported(varName) {
		log.Fatalf("failed to convert property name to exported identifier: %q", origName)
	}

	return varName, key
}
