// Code generated by Herebyfile.mjs generate:enums from internal/ast/tokenflags.go. DO NOT EDIT.
export var TokenFlags: any;
(function (TokenFlags) {
    TokenFlags[TokenFlags["None"] = 0] = "None";
    TokenFlags[TokenFlags["PrecedingLineBreak"] = 1] = "PrecedingLineBreak";
    TokenFlags[TokenFlags["PrecedingJSDocComment"] = 2] = "PrecedingJSDocComment";
    TokenFlags[TokenFlags["Unterminated"] = 4] = "Unterminated";
    TokenFlags[TokenFlags["ExtendedUnicodeEscape"] = 8] = "ExtendedUnicodeEscape";
    TokenFlags[TokenFlags["Scientific"] = 16] = "Scientific";
    TokenFlags[TokenFlags["HexSpecifier"] = 64] = "HexSpecifier";
    TokenFlags[TokenFlags["UnicodeEscape"] = 1024] = "UnicodeEscape";
    TokenFlags[TokenFlags["ContainsInvalidEscape"] = 2048] = "ContainsInvalidEscape";
    TokenFlags[TokenFlags["HexEscape"] = 4096] = "HexEscape";
    TokenFlags[TokenFlags["ContainsLeadingZero"] = 8192] = "ContainsLeadingZero";
    TokenFlags[TokenFlags["PrecedingJSDocLeadingAsterisks"] = 32768] = "PrecedingJSDocLeadingAsterisks";
    TokenFlags[TokenFlags["SingleQuote"] = 65536] = "SingleQuote";
    TokenFlags[TokenFlags["PrecedingJSDocWithDeprecated"] = 131072] = "PrecedingJSDocWithDeprecated";
    TokenFlags[TokenFlags["PrecedingJSDocWithSeeOrLink"] = 262144] = "PrecedingJSDocWithSeeOrLink";
    TokenFlags[TokenFlags["WordOperator"] = 524288] = "WordOperator";
    TokenFlags[TokenFlags["WithSpecifier"] = 64] = "WithSpecifier";
    TokenFlags[TokenFlags["StringLiteralFlags"] = 72716] = "StringLiteralFlags";
    TokenFlags[TokenFlags["NumericLiteralFlags"] = 8272] = "NumericLiteralFlags";
    TokenFlags[TokenFlags["TemplateLiteralLikeFlags"] = 7180] = "TemplateLiteralLikeFlags";
    TokenFlags[TokenFlags["RegularExpressionLiteralFlags"] = 4] = "RegularExpressionLiteralFlags";
    TokenFlags[TokenFlags["IsInvalid"] = 10240] = "IsInvalid";
})(TokenFlags || (TokenFlags = {}));
