// Code generated by Herebyfile.mjs generate:enums from internal/checker/types.go. DO NOT EDIT.
export var TypePredicateKind: any;
(function (TypePredicateKind) {
    TypePredicateKind[TypePredicateKind["Identifier"] = 0] = "Identifier";
    TypePredicateKind[TypePredicateKind["AssertsIdentifier"] = 1] = "AssertsIdentifier";
})(TypePredicateKind || (TypePredicateKind = {}));
